[package]
name = "search_canister"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.1"
ic-cdk-macros = "0.6.9"
search = { path = "../search" }

[dev-dependencies]
