[package]
name = "search_canister"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.10"
ic-cdk = "0.17.0"
ic-cdk-macros = "0.17.0"
search = { path = "../search" }

[dev-dependencies]
