// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    motoko: [
      {
        type: "category",
        label: "Motoko language book",
        items: [
          {
            type: "link",
            label: "1. Introduction",
            href: "https://motoko-book.dev/introduction.html",
          },
          {
            type: "link",
            label: "2. Common programming concepts",
            href: "https://motoko-book.dev/common-programming-concepts.html",
          },
          {
            type: "link",
            label: "3. Internet Computer programming concepts",
            href: "https://motoko-book.dev/internet-computer-programming-concepts.html",
          },
          {
            type: "link",
            label: "4. Advanced types",
            href: "https://motoko-book.dev/advanced-types.html",
          },
          {
            type: "link",
            label: "5. The base library",
            href: "https://motoko-book.dev/base-library.html",
          },
          {
            type: "link",
            label: "6. Advanced concepts",
            href: "https://motoko-book.dev/advanced-concepts.html",
          },
        ],
      },
      {
        type: "autogenerated",
        dirName: "motoko",
      },
    ],
  };
  
  /**
   * Add UI tests in development mode
   */
  if (process.env.NODE_ENV === "development") {
    sidebars["__ui_tests_internal__"] = [
      {
        type: "autogenerated",
        dirName: "tests",
      },
    ];
  }
  
  module.exports = sidebars;
  