import { SampleItem } from "@site/src/components/Common/sampleItems";

const communityProjects: SampleItem[] = [
  {
    index: 0,
    title: "Spinner Cash",
    body: "Safeguard your financial privacy with zero-knowledge proofs",
    links: {
      github: "https://github.com/spinner-cash/spinner",
      livePreview: "https://spinner.cash",
      external: "https://supernova.devpost.com/submissions/327085-spinner-cash",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/spinner-cash.png",
  },
  {
    index: 1,
    title: "Kontribute",
    body: "Kontribute brings readers, writers and NFTs together. Write some lore for your NFT collection or support your favourite writer by buying their NFTs - Web 3.0 creative writing with NFTs",
    links: {
      github: "https://github.com/teambonsai/bonsai_dapp",
      livePreview: "https://3ezq7-iqaaa-aaaal-aaacq-cai.raw.ic0.app/",
      external: "https://supernova.devpost.com/submissions/326818-kontribute",
      otherLinks: ["https://mobile.twitter.com/TeamBonsai_ICP"],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/kontribute.png",
  },
  {
    index: 2,
    title: "dSquad",
    body: "A new chapter of the Internet is opening. Start by minting your avatar, then take part in the adventure and get rewarded as your explore a new wave of decentralized applications.",
    links: {
      github: "https://github.com/ICPSquad/Squad",
      livePreview: "https://x3ul6-2aaaa-aaaah-abjda-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/328183-dsquad",
      otherLinks: [
        "https://dsquad.gitbook.io/docs/",
        "https://entrepot.app/marketplace/icpsquad2",
        "https://twitter.com/dSquadNFT",
      ],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/dsquad.png",
  },
  {
    index: 3,
    title: "ICTC",
    body: "IC Transaction Coordinator (ICTC) is a distributed transaction framework for Defi applications on IC network. It supports Motoko language. The core idea of ICTC is inspired by the DTC (Distributed Transaction Coordinator), which is commonly used in the financial sector.",
    links: {
      github: "https://github.com/iclighthouse/ICTC",
      livePreview: "https://cmqwp-uiaaa-aaaaj-aihzq-cai.raw.ic0.app",
      external: "https://supernova.devpost.com/submissions/328779-ictc",
      otherLinks: ["https://youtu.be/fxG4vunET8s"],
    },
    languages: ["motoko"],
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ictc.png",
  },
  {
    index: 4,
    title: "Proof of Personhood",
    body: "a Sybil-proof identity system powered by decentralized AI human detection.",
    links: {
      github: "https://github.com/AstroxNetwork/Proof-of-Personhood",
      livePreview: "http://thehuman.id/",
      external:
        "https://supernova.devpost.com/submissions/332526-proof-of-personhood",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/proof-of-personhood.png",
  },
  {
    index: 5,
    title: "Kinic",
    body: "A search engine for Web3.",
    links: {
      github: "https://github.com/wyattbenno777/kinic",
      livePreview: "https://kinic.io/",
      external: "https://supernova.devpost.com/submissions/327859-kinic",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/kinic.png",
  },
  {
    index: 6,
    title: "Signals",
    body: "A unique SocialFi space for making connections, discovering events and creating decentralized communities. Signals is a DAO. The more you interact with it, the greater say you have in its governance.",
    links: {
      github: "https://github.com/bertiespell/Signals",
      livePreview: "https://2fydv-iqaaa-aaaak-qap6q-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/327368-signals",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["rust", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/signals.png",
  },
  {
    index: 7,
    title: "FaeFolk",
    body: "FaeFolk is an NFT-based role-playing game where you use your NFTs to craft tools & equipment, train your skills and ultimately fight your way through dungeons and find treasure.",
    links: {
      github: "https://github.com/ICCards/faefolk",
      livePreview: "https://ge5fs-qyaaa-aaaap-qam6a-cai.raw.ic0.app/",
      external: "https://supernova.devpost.com/submissions/326797-faefolk",
      otherLinks: ["https://github.com/ICCards/Server"],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["rust", "motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/faefolk.png",
  },
  {
    index: 8,
    title: "Saga Tarot",
    body: "Open source tarot ecosystem on the IC. Nobody owns Tarot. Everybody owns Web3.",
    links: {
      github: "https://github.com/sagacards/bazaar",
      livePreview: "https://l2jyf-nqaaa-aaaah-qadha-cai.raw.ic0.app/",
      external: "https://supernova.devpost.com/submissions/334420-saga-tarot",
      otherLinks: [
        "https://bazaar.saga.cards",
        "https://table.saga.cards",
        "https://directory.saga.cards",
        "https://www.npmjs.com/settings/opentarot/packages",
        "https://github.com/sagacards/legends-nft",
      ],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/saga-tarot.png",
  },
  {
    index: 9,
    title: "Enoki DEX",
    body: "Completely Async and Scalable DEX: Swap, Earn, and be a Market Maker",
    links: {
      github: "https://github.com/enoki-dex",
      livePreview: "https://5ba5l-caaaa-aaaag-qaoja-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/334178-enoki-dex",
      otherLinks: ["https://enoki.ooo"],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/enoki-dex.png",
  },
  {
    index: 10,
    title: "ICMaps",
    body: "ICMaps brings maps to the internet computer. With the ICMaps frontend you can install your own map server provided by ICMaps on Canister and integrate maps into Web3, Web2 and even desktop GIS apps.",
    links: {
      github: "https://github.com/stumpigit/icmaps",
      livePreview: "https://discord.gg/PruV4RxD9S",
      external: "https://supernova.devpost.com/submissions/326804-icmaps",
      otherLinks: ["https://icmaps.org"],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/icmaps.png",
  },
  {
    index: 11,
    title: "CanDB",
    body: "Meet CanDB, the first flexible and truly horizontally scalable NoSQL database built for the Internet Computer.\n\nhttps://www.canscale.dev",
    links: {
      github: "https://github.com/canscale/supernova-candb-demo",
      livePreview: "https://pliqr-fqaaa-aaaan-qalpq-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/327567-candb",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/candb.jpeg",
  },
  {
    index: 12,
    title: "STKRS",
    body: "Stkrs is the social identity app for Web 3.0. Users can express themselves, trust others online, and revolutionize our governance, all while being anon and maintaining privacy.",
    links: {
      github: "https://github.com/arjunpat/stkrs.me",
      livePreview: "https://priqv-iqaaa-aaaak-ab4rq-cai.ic0.app/#/",
      external: "https://supernova.devpost.com/submissions/333208-stkrs",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/stkrs.png",
  },
  {
    index: 13,
    title: "Paws Arena - Multiplayer PVP Play to Earn",
    body: "This is the cutest, most fun and competitive turn-based play to earn multiplayer game on the ICP. Players will fight in the arena and earn $PAW Tokens which will be used to buy in-game items.",
    links: {
      github: "https://github.com/icla692/paws_arena_ickitties",
      livePreview: "https://knbkj-fiaaa-aaaan-qaadq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/333263-paws-arena-multiplayer-pvp-play-to-earn",
      otherLinks: [
        "https://linktr.ee/ickitties",
        "https://twitter.com/ICKitties/status/1469684414359683077?s=20&t=4ES-GxYs0keCC_mjVCGWVA",
      ],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image:
      "/img/community-projects/paws-arena-multiplayer-pvp-play-to-earn.jpg",
  },
  {
    index: 14,
    title: "IC Avatar Creator",
    body: "The IC Avatar Creator allows users to create and manage avatars for the open metaverse. The project includes GLB avatars that are minted to the Internet Computer using the DIP721v2 token standard.",
    links: {
      github: "https://github.com/AtlasFoundation/AvatarCreator-IC-Project",
      external:
        "https://supernova.devpost.com/submissions/331595-ic-avatar-creator",
      otherLinks: ["https://www.npmjs.com/package/avatarcreator"],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["rust", "motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/ic-avatar-creator.jpg",
  },
  {
    index: 15,
    title: "metamob",
    body: "Create, donate, vote, sign and fund extraordinary mobilizations!",
    links: {
      github: "https://github.com/av1ctor/metamob",
      livePreview: "https://wbpm2-ciaaa-aaaan-qajta-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/327261-metamob",
      otherLinks: ["https://github.com/av1ctor/mo-table"],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/metamob.png",
  },
  {
    index: 16,
    title: "FoxIC",
    body: "A tool allowing MetaMask users to enter IC ecosystem",
    links: {
      github: "https://github.com/AstroxNetwork/FoxIC",
      livePreview: "https://ip5qp-gaaaa-aaaah-ablla-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/334321-foxic",
      otherLinks: ["https://github.com/AstroxNetwork/ICSnap"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/foxic.jpg",
  },
  {
    index: 17,
    title: "GalacticWar",
    body: "GalacticWar is a novel protocol that mixes NFT, Gaming and DEFI .",
    links: {
      github: "https://github.com/harshu4/GalacticWar",
      livePreview: "https://rlx5r-ziaaa-aaaal-qa7qq-cai.raw.ic0.app/",
      external: "https://supernova.devpost.com/submissions/334597-galacticwar",
      otherLinks: [
        "https://uqnba-7yaaa-aaaal-qa7pq-cai.raw.ic0.app/",
        "https://a4gq6-oaaaa-aaaab-qaa4q-cai.raw.ic0.app/?id=tdja5-gyaaa-aaaag-aaoeq-cai",
      ],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/galacticwar.png",
  },
  {
    index: 18,
    title: "DeTi: Decentralized Time Travel",
    body: "Run code on your canister in the future!",
    links: {
      github: "https://github.com/akshay-rakheja/supernova2022",
      livePreview: "https://fl5mh-daaaa-aaaap-qalja-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/332847-deti-decentralized-time-travel",
      otherLinks: [
        "https://d7hzd-wiaaa-aaaap-qamba-cai.ic0.app/",
        "https://npmjs.com/package/@raydeck/useplug",
      ],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["typescript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/deti:-decentralized-time-travel.png",
  },
  {
    index: 19,
    title: "NFT Exchange",
    body: "The NFT Exchange for Web 3.0",
    links: {
      github: "https://github.com/IC-Difinity-Project",
      livePreview: "https://eytcp-gaaaa-aaaap-aagna-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/333058-nft-exchange",
      otherLinks: [
        "https://docs.google.com/presentation/d/104xr9WEgrpsZqwqPxQBZA-PNJUYNMei3kbQ7aqJz16I/edit?usp=sharing",
      ],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/nft-exchange.jpg",
  },
  {
    index: 20,
    title: "iLearnX Beyond Web3 (By Yaruhito Project)",
    body: "We offer all-in-one Web3developer learning platform: roadmap, course materials, learning community, support system&hackathon opportunity hosted on ICP for aspired Web3 developers/challengers.",
    links: {
      github: "https://github.com/AcmeGamer/IPEX",
      livePreview: "https://aac5l-aiaaa-aaaam-qaqla-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334237-ilearnx-beyond-web3-by-yaruhito-project",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image:
      "/img/community-projects/ilearnx-beyond-web3-(by-yaruhito-project).png",
  },
  {
    index: 21,
    title: "Cronacle + Freeos: A cross-chain oracle for a democratic UBI",
    body: "Freeos, a democratic UBI—where participants steer the economy through a democratically elected monetary policy each week—connects to a novel type of decentralised, cross-chain oracle called Cronacle",
    links: {
      github: "https://github.com/orgs/FreeosDAO/repositories",
      livePreview: "https://xwqat-7aaaa-aaaad-qafaq-cai.raw.ic0.app",
      external:
        "https://supernova.devpost.com/submissions/329755-cronacle-freeos-a-cross-chain-oracle-for-a-democratic-ubi",
      otherLinks: [
        "https://medium.com/freedao/freeos-supernova-guide-2577d747b423",
        "https://www.protonscan.io/account/cronacle?loadContract=true&tab=Tables&account=cronacle&scope=cronacle&limit=100&table=prices",
      ],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image:
      "/img/community-projects/cronacle-+-freeos:-a-cross-chain-oracle-for-a-democratic-ubi.jpg",
  },
  {
    index: 22,
    title: "NnsDAO Protocol",
    body: "NnsDAO is a boundaryless autonomous organization, which provides some basic modular programmable services for building the world of DAOn.",
    links: {
      github: "https://github.com/NnsDao/nnsdao_sdk",
      livePreview: "https://h637e-ziaaa-aaaaj-aaeaa-cai.raw.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/326858-nnsdao-protocol",
      otherLinks: ["https://github.com/NnsDao/nomos-v1"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust", "motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/nnsdao-protocol.png",
  },
  {
    index: 23,
    title: "པ་ཀྲ་ཧེ་། Bazahei: The first ICP-XRP cross-chain NFT",
    body: "We pioneer a general cross-chain NFT solution from IC to XRP to promote the regional and under-represented culture.",
    links: {
      github: "https://github.com/Itoka-DAO/IC-XRP",
      livePreview: "https://aack7-jaaaa-aaaai-acl6a-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/329724-bazahei-the-first-icp-xrp-cross-chain-nft",
      otherLinks: [
        "https://github.com/Itoka-DAO/xrp_server",
        "https://github.com/Itoka-DAO/icxrp",
      ],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image:
      "/img/community-projects/bazahei:-the-first-icp-xrp-cross-chain-nft.png",
  },
  {
    index: 24,
    title: "SIGMA DEFI",
    body: "SIGMA DEFI is a DeFi service and tool for developers and investors interested in IC,providing services without coding1. Multi sender2. Create DIP 203. Generate NFT and mint4. Fiat Gateways",
    links: {
      github: "https://github.com/TheVanquiser/SIGMADEFI",
      external: "https://supernova.devpost.com/submissions/329753-sigma-defi",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/sigma-defi.png",
  },
  {
    index: 25,
    title: "IC Web3D Engine",
    body: "A lightweight game engine fully deployed on the IC.Users can easily create their own decentralized games or other 3D application scenarios on the IC with some simple operations",
    links: {
      github: "https://github.com/IC-Web3D-Engine",
      livePreview: "https://q7vk3-myaaa-aaaak-qarcq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334588-ic-web3d-engine",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["javascript", "motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ic-web3d-engine.png",
  },
  {
    index: 26,
    title: "Texas Hold'em",
    body: 'There is a famous saying in Texas Hold\'em: "Victory comes not from your opponent making more mistakes, but from you making fewer".',
    links: {
      github: "https://github.com/NnsDao/ICTexas-UI",
      livePreview: "https://lm5fh-ayaaa-aaaah-aafua-cai.raw.ic0.app/#/",
      external:
        "https://supernova.devpost.com/submissions/334184-texas-hold-em",
      otherLinks: [],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/texas-hold'em.png",
  },
  {
    index: 27,
    title: "MUSALL",
    body: "Music ownership is broken! At MUSALL we aim to change ownership to a shared model. Musicians create a contract that is fair and transparent. Fans purchase said contracts. All earn through royalties.",
    links: {
      github: "https://github.com/fowlerlee/musall",
      external: "https://supernova.devpost.com/submissions/334192-musall",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/musall.png",
  },
  {
    index: 28,
    title: "News Bias Check",
    body: "Decentralised application to help combat fake news and reduce bias in information consumption. Chrome extension that uses backend on IC network shows bias/accuracy info about all news articles online.",
    links: {
      github: "https://github.com/jayshreeanand/news-bias-check",
      livePreview: "https://77oii-eaaaa-aaaal-aaydq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334583-news-bias-check",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/news-bias-check.jpeg",
  },
  {
    index: 29,
    title: "Questions & Answers",
    body: "Ask Questions.. Share Answers.. Earn Coins..",
    links: {
      github: "https://github.com/7flash/internet-computer-dapp",
      livePreview: "https://u75p2-siaaa-aaaap-aafaq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/327670-questions-answers",
      otherLinks: ["https://youtu.be/lBz4g-gow2E"],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/questions-and-answers.jpg",
  },
  {
    index: 30,
    title: "Cratch",
    body: "The Future of Content Creation",
    links: {
      github: "https://github.com/skidrow8852/Cratch_Platform_V1",
      livePreview: "https://cratch.io/",
      external: "https://supernova.devpost.com/submissions/330315-cratch",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/cratch.png",
  },
  {
    index: 31,
    title: "Leap",
    body: "Leap is a market for information. Existing online forums have little incentives for users to provide high-quality answers. Leap allows users to reward others financially to get great answers quickly.",
    links: {
      github: "https://github.com/Matlor/Information-Market",
      external: "https://supernova.devpost.com/submissions/334221-leap",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/leap.gif",
  },
  {
    index: 32,
    title: "MetaBio",
    body: "MetaBio is a Web3 application to connect gardeners, farmers to crypto world. We aim to be the leading Web3 application for gardening communities and their data to enterprise or biology experts.",
    links: {
      github: "https://github.com/viefam/metabio-ic",
      livePreview: "https://testflight.apple.com/join/M6DTlUAc",
      external: "https://supernova.devpost.com/submissions/329759-metabio",
      otherLinks: [
        "https://drive.google.com/file/d/1Ky1aIM3PbbabwFdjyUjXSkz2edAbHbKc/view",
      ],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/metabio.png",
  },
  {
    index: 33,
    title: "Donainvest",
    body: "Donainvest is a donation-investment platform on which the market cap is in proportion to the social impact and social workers are able to continuously fundraise without crypto-related licenses.",
    links: {
      github: "https://github.com/kentomisawa/donainvest",
      livePreview:
        "https://xd.adobe.com/view/da9964cd-a5e2-4ee0-bd15-c4898d792175-8fca/",
      external: "https://supernova.devpost.com/submissions/334181-donainvest",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/donainvest.gif",
  },
  {
    index: 34,
    title: "IC1101 iUSD",
    body: "MakerDAO with no jokes.",
    links: {
      github: "https://github.com/ic1101-iusd",
      livePreview: "https://mk2a2-miaaa-aaaak-aavra-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/329970-ic1101-iusd",
      otherLinks: [
        "https://docs.google.com/presentation/d/1cHaNDOccipyeUVnzGdDNQi1p8BO2KupqpuSSfZJRJaE/edit?usp=sharing",
      ],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ic1101-iusd.jpeg",
  },
  {
    index: 35,
    title: "Secure Canister Communication on the IC Blockchain",
    body: "We provide a framework where sensitive messages can be securely passed between canisters, i.e to avoid man-in-the-middle attacks. Our solution allows secrets to be securely communicated.",
    links: {
      github:
        "https://github.com/MaithreyaSitaraman/secure_canister_communication_IC_blockchain",
      external:
        "https://supernova.devpost.com/submissions/333088-secure-canister-communication-on-the-ic-blockchain",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image:
      "/img/community-projects/secure-canister-communication-on-the-ic-blockchain.png",
  },
  {
    index: 36,
    title: "Exponent",
    body: "Exponent is a suite of products that make NFTs easy for creators and game developers. Exponent currently consists of an NFT canister standard (next gen. EXT standard) and a CLI tool for developers.",
    links: {
      github: "https://github.com/Toniq-Labs/exponent-cli",
      external: "https://supernova.devpost.com/submissions/334153-exponent",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/exponent.gif",
  },
  {
    index: 37,
    title: "Ontics",
    body: "Authoritative source of release images of all blockchain technologies",
    links: {
      github: "https://github.com/KOSASIH/Ontics",
      external: "https://supernova.devpost.com/submissions/326882-ontics",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/ontics.png",
  },
  {
    index: 38,
    title: "planzApp",
    body: "A DApp that enables users to make everyday plans within a smart, connected and decentralized economy",
    links: {
      github: "https://github.com/SuperNova-Planzapp/planzapp_reactjs",
      livePreview: "https://gr2u7-rqaaa-aaaap-qam5q-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/326834-planzapp",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/planzapp.jpeg",
  },
  {
    index: 39,
    title: "Landlord",
    body: "Landlord is a DApp where users can trade and invest in real-estate easily & securely. It eliminates the risk of real-estate scam, and creates a safe heaven where sellers can sell, buyers can buy etc.",
    links: {
      github: "https://github.com/landlord-limited",
      external: "https://supernova.devpost.com/submissions/327503-landlord",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/landlord.jpg",
  },
  {
    index: 40,
    title: "DeSu - Decentralized Survey App",
    body: "A decentralized platform for conducting paid and unpaid surveys that incentivizes the traditional survey-taking process and has something in store for both the parties in it.",
    links: {
      github:
        "https://github.com/decentrazone/DeSu-Decentralised-Survey-Platform-Supernova/",
      livePreview: "https://i3h6n-siaaa-aaaap-aahaq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/333957-desu-decentralized-survey-app",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/desu-decentralized-survey-app.png",
  },
  {
    index: 41,
    title: "ICES",
    body: "a storage and analysis service for canister's event logs on IC",
    links: {
      github: "https://github.com/icpfans-xyz/ices",
      livePreview: "https://ices.one/",
      external: "https://supernova.devpost.com/submissions/334450-ices",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko", "rust", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ices.png",
  },
  {
    index: 42,
    title: "dfxIoT",
    body: "Connecting real-world data into Internet Computer using verifiable and trusted IoT Devices and incentivize data-providers with tokens",
    links: {
      github: "https://github.com/marspoolxyz/dfx2IoT",
      livePreview:
        "https://docs.google.com/presentation/d/10-LrMCVAyKQaRLiBvnQ2mJ6oyzoAopacayWexG3GJs8/edit?usp=sharing",
      external: "https://supernova.devpost.com/submissions/334289-dfxiot",
      otherLinks: ["https://bit.ly/SuperNova_dfxIoT"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/dfxiot.jpeg",
  },
  {
    index: 43,
    title: "Dear Diary",
    body: "Dear Diary is the first decentralized market place that will allow users to sell their diaries as NFTs. It is developed on Web3 on the Internet Computer, Motoko backend and React.js frontend.",
    links: {
      github: "https://github.com/nahrinoda/dear-diary",
      external: "https://supernova.devpost.com/submissions/327321-dear-diary",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/dear-diary.png",
  },
  {
    index: 44,
    title: "Sustainations DAO",
    body: "The first SDG (Sustainable Development Goals) DAO on Dfinity. \n💚 SUSTAINATIONS is a global DAO of change-makers, and builders who work together to write a greener future for the Earth.",
    links: {
      github: "http://github.com/triipme/sustainations_dao",
      livePreview: "https://youtu.be/pe84UGSXOuk",
      external:
        "https://supernova.devpost.com/submissions/329671-sustainations-dao",
      otherLinks: ["http://sustainations.com/"],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/sustainations-dao.jpeg",
  },
  {
    index: 45,
    title: "Tourapin",
    body: "Vacation guides by your favorite travel influencers",
    links: {
      github: "https://github.com/BreeDay/Tourapin",
      external: "https://supernova.devpost.com/submissions/334356-tourapin",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/tourapin.png",
  },
  {
    index: 46,
    title: "IC Birds",
    body: "Play with you IC Birds nfts on our decentralized games. Collect tokens and improve your birds skills to beat your best score and grind the leaderboard !",
    links: {
      github: "https://github.com/leo-ship-it/icbirds-public",
      livePreview: "https://yqtpa-pqaaa-aaaan-qadba-cai.ic0.app/home",
      external: "https://supernova.devpost.com/submissions/328423-ic-birds",
      otherLinks: [],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["motoko", "javascript", "rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ic-birds.png",
  },
  {
    index: 47,
    title: "Candid+",
    body: "Candid+ is the better Candid UI with test cases and logging. To build the hub for IC developers and enterprises, we will integrate the entire lifecycle of the development for canisters.",
    links: {
      github: "https://github.com/Astrapolis/ICHub",
      livePreview: "https://4cmdj-pqaaa-aaaal-qa62a-cai.ic0.app",
      external: "https://supernova.devpost.com/submissions/330304-candid",
      otherLinks: ["http://hub.icp.xyz"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/candid+.jpg",
  },
  {
    index: 48,
    title: "Honest Ticket Machine",
    body: "We’re building the tools to empower creators to work without fear of copyright and encourage collaboration rather than competition over IP.",
    links: {
      github: "https://github.com/Amata-World-Hackathons/honest-ticket-machine",
      livePreview: "https://mymdv-biaaa-aaaan-qam2q-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/333151-honest-ticket-machine",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/honest-ticket-machine.png",
  },
  {
    index: 49,
    title: "Splash",
    body: "Figma for Web3",
    links: {
      github: "https://github.com/gupnik/splash",
      livePreview: "https://d6uqw-tyaaa-aaaap-aag5q-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/331672-splash",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/splash.png",
  },
  {
    index: 50,
    title: "icApps",
    body: "Internet Computer projects community portal 🌀",
    links: {
      github: "https://github.com/tomkoom/icApps",
      livePreview: "https://n7ib3-4qaaa-aaaai-qagnq-cai.raw.ic0.app/#/",
      external: "https://supernova.devpost.com/submissions/328318-icapps",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/icapps.png",
  },
  {
    index: 51,
    title: "Ceto",
    body: "The first order book trading platform of fractional noun-fungible tokens(F-NFTs) and a professional marketplace for crypto collectibles.",
    links: {
      github: "https://github.com/Ceto-Labs",
      livePreview: "https://4jz7p-7yaaa-aaaai-qhobq-cai.raw.ic0.app/",
      external: "https://supernova.devpost.com/submissions/326863-ceto",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust", "motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ceto.jpg",
  },
  {
    index: 52,
    title: "Symposium Futura",
    body: "a community owned blog that curates and incentivizes exceptional content on philosophy, scientific inquiry, and the future of tech",
    links: {
      github: "https://github.com/mourginakis/symposium_futura",
      livePreview: "https://mzgdj-vqaaa-aaaag-qanaa-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/330681-symposium-futura",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/symposium-futura.png",
  },
  {
    index: 53,
    title: "ICLand",
    body: "ICLand powers tokenized communities by connecting Web3 identities to social spaces & delivering key token data to communities. First tools: Discord token holder verification; sales & listings bot.",
    links: {
      github: "https://github.com/renartlabsicp",
      livePreview: "https://kwuck-oaaaa-aaaad-qcsja-cai.ic.fleek.co/",
      external: "https://supernova.devpost.com/submissions/334115-icland",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/icland.png",
  },
  {
    index: 54,
    title: "Mixverse",
    body: "Curate your space, Enjoy metaverse!",
    links: {
      github: "https://github.com/mix-labs/",
      livePreview:
        "https://drive.google.com/file/d/1F7BRVkyRiKCV9xZ_Vdsl3TF2JqjCq_os/view",
      external: "https://supernova.devpost.com/submissions/334372-mixverse",
      otherLinks: ["https://mixverse.vercel.app/"],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/mixverse.png",
  },
  {
    index: 55,
    title: "Metaspeare",
    body: "Allowing users to mix NFTs to mint a new one with properties from the parent NFTs genome.",
    links: {
      github: "https://github.com/BreeDay/Metaspeare",
      external: "https://supernova.devpost.com/submissions/334594-metaspeare",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/metaspeare.png",
  },
  {
    index: 56,
    title: "Meta Yield - liquid staking crowdfunding platform for ICP.",
    body: "Meta Yield fundraising mechanism leverages staking, ICP backers only exchange their future Neuron rewards for a project’s token and get to keep their ICP, thus de-risking the crowdfunding process.",
    links: {
      github: "https://github.com/Narwallets/meta-yield-ic",
      external:
        "https://supernova.devpost.com/submissions/326851-meta-yield-liquid-staking-crowdfunding-platform-for-icp",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image:
      "/img/community-projects/meta-yield-liquid-staking-crowdfunding-platform-for-icp..png",
  },
  {
    index: 57,
    title: "Bonsai ICP",
    body: "A GameFi in Internet Computer platform",
    links: {
      github: "https://github.com/conglt10/bonsai-icp",
      external: "https://supernova.devpost.com/submissions/333311-bonsai-icp",
      otherLinks: [],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["rust", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/bonsai-icp.png",
  },
  {
    index: 58,
    title: "C3-Protocol (Co-Created Collectibles)",
    body: "CCC is a platform for on-chain creation and collaboration. It takes advantage of Dfinity’s low threshold in order to introduce Web2 creators to Web3.",
    links: {
      github: "https://github.com/C3-Protocol/CoCreate",
      external:
        "https://supernova.devpost.com/submissions/334205-c3-protocol-co-created-collectibles",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko", "rust", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/c3-protocol-(co-created-collectibles).png",
  },
  {
    index: 59,
    title: "iCAN",
    body: "What is iCAN? -- The best easy-to-use Canister Management Platform on IC.",
    links: {
      github: "https://github.com/PrimLabs/iCAN",
      external: "https://supernova.devpost.com/submissions/329653-ican",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust", "motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/ican.jpg",
  },
  {
    index: 60,
    title: "ICX",
    body: "Web2sites Organizing-Tool for web2.5ers built by web3ers.",
    links: {
      github: "https://github.com/Mulander-J/icx",
      livePreview: "https://jeksq-wyaaa-aaaal-qaw3a-cai.ic0.app",
      external: "https://supernova.devpost.com/submissions/326854-icx",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/icx.png",
  },
  {
    index: 61,
    title: "Cash Cow",
    body: 'Lending & Borrowing DeFi Dapp built on ICP with Motoko "Moo"-ving at the speed of business',
    links: {
      github: "https://github.com/lucylow/Cash_Cow",
      livePreview: "https://gzz56-daaaa-aaaal-qai2a-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/333891-cash-cow",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/cash-cow.gif",
  },
  {
    index: 62,
    title: "SMORF",
    body: "simple dao factory for small self-managed organisations & communities (up to 1000 members).",
    links: {
      github: "https://github.com/ioustamora/smorf",
      external: "https://supernova.devpost.com/submissions/329999-smorf",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/smorf.png",
  },
  {
    index: 63,
    title: "DECOLLAB",
    body: "DECOLLAB offers a singular, streamlined platform for coders to seamlessly work on projects together quickly and effectively.",
    links: {
      github: "https://github.com/ashwinr000/DECOLLAB",
      external: "https://supernova.devpost.com/submissions/334270-decollab",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["javascript", "motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/decollab.png",
  },
  {
    index: 64,
    title: "Arena Project",
    body: "The project sets out to create a game that hosts its entire backend and executes logic within the IC. The project continues to expand and game-agnostic, engine features can be used by other games.",
    links: {
      github: "https://github.com/wasolomon98/ArenaProject",
      external:
        "https://supernova.devpost.com/submissions/334296-arena-project",
      otherLinks: [],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/arena-project.gif",
  },
  {
    index: 65,
    title: "PRESTO: Escrow, Title, & Trust dApp",
    body: "Presto is an Internet Computer dApp for creating and managing escrows & trusts and for registering ownership of any type of property on-chain.",
    links: {
      github: "https://github.com/hafezrouzati/presto",
      livePreview: "https://3us5k-qyaaa-aaaak-qap3a-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/330797-presto-escrow-title-trust-dapp",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/presto:-escrow-title-and-trust-dapp.png",
  },
  {
    index: 66,
    title: "CyclesDAO frontend",
    body: "The CyclesDAO is a configurable canister that allows to decentralize the powering-up of your canisters by giving to people who send cycles rewards and power in the governance.",
    links: {
      github: "https://github.com/sardariuss/CyclesDAO",
      external:
        "https://supernova.devpost.com/submissions/328532-cyclesdao-frontend",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/cyclesdao-frontend.png",
  },
  {
    index: 67,
    title: "Veta",
    body: "Bringing data ownership back to its user",
    links: {
      github: "https://github.com/sworks89/veta",
      livePreview: "http://veta.icp.xyz/",
      external: "https://supernova.devpost.com/submissions/334489-veta",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/veta.jpg",
  },
  {
    index: 68,
    title: "dfx agent",
    body: "A easy way to learn & execute internet computer dfx commands.",
    links: {
      github: "https://github.com/samshi/dfx-agent",
      external: "https://supernova.devpost.com/submissions/333096-dfx-agent",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/dfx-agent.png",
  },
  {
    index: 69,
    title: "DaoWorld",
    body: "First #Dao management tool on IC, welcome any project that needs funds, community, and governance.",
    links: {
      github: "https://github.com/ic-daow/daow",
      livePreview: "https://e6np3-zyaaa-aaaah-aapaq-cai.raw.ic0.app",
      external: "https://supernova.devpost.com/submissions/330705-daoworld",
      otherLinks: [
        "https://twitter.com/DfinityDaoWorld",
        "https://www.youtube.com/watch?v=0R1dziSG6K0",
      ],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust", "motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/daoworld.gif",
  },
  {
    index: 70,
    title: "DeSwap Orderbook",
    body: "An Order Matching Engine Module for Dex in Motoko.",
    links: {
      github: "https://github.com/iclighthouse/DeSwap-Orderbook",
      livePreview: "https://pk6zh-iiaaa-aaaaj-ainda-cai.raw.ic0.app",
      external:
        "https://supernova.devpost.com/submissions/334440-deswap-orderbook",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/deswap-orderbook.png",
  },
  {
    index: 71,
    title: "Doap",
    body: "Bringing POAP (proof of participation) to the Internet Computer",
    links: {
      github: "https://github.com/picsoung/doap-dfinity",
      external: "https://supernova.devpost.com/submissions/334336-doap",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
  },
  {
    index: 73,
    title: "Dmail Network",
    body: "Construct DID in Web 3.0, Not Just an Email. Will be a basic infrastructure tool, flow portal and DID for users to come into the Web 3.0 era.",
    links: {
      github: "https://github.com/dmailoffcial",
      livePreview: "https://evyc3-ziaaa-aaaak-aam5a-cai.ic0.app/inbox",
      external:
        "https://supernova.devpost.com/submissions/326888-dmail-network",
      otherLinks: [
        "https://dmail.ai/",
        "https://dmail.ai/presale",
        "https://twitter.com/dmailofficial",
        "https://discord.gg/QbvaeqwMFg",
        "https://medium.com/@dmail_official",
      ],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["rust", "motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/dmail-network.png",
  },
  {
    index: 74,
    title: "ICP.NET",
    body: "C#/.NET candid and http agent library",
    links: {
      github: "https://github.com/Gekctek/ICP.NET",
      livePreview:
        "https://f76k2-siaaa-aaaal-aaoba-cai.raw.ic0.app/d/icp-for-dotnet-developers",
      external: "https://supernova.devpost.com/submissions/329814-icp-net",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["other"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/icp.net.gif",
  },
  {
    index: 75,
    title: "Candid Intellij Plugin",
    body: "A Candid language plugin that provide a complete support to efficiently edit .did files.",
    links: {
      github: "https://github.com/Alaanor/candid-intellij-plugin",
      external:
        "https://supernova.devpost.com/submissions/331891-candid-intellij-plugin",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["other"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/candid-intellij-plugin.png",
  },
  {
    index: 76,
    title: "MOPS",
    body: "Motoko package manager with on-chain package registry",
    links: {
      github: "https://github.com/ZenVoich/mops",
      livePreview: "https://distrikt.app/u/mops",
      external: "https://supernova.devpost.com/submissions/327907-mops",
      otherLinks: ["http://mops.one/", "https://twitter.com/mops_one"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/mops.png",
  },
  {
    index: 77,
    title: "Sand Bless Unction",
    body: "Bless your artwork using owned crypto-marks.",
    links: {
      github: "https://github.com/branciard/sandblessunction",
      livePreview: "https://qob3k-7yaaa-aaaao-aahdq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/333601-sand-bless-unction",
      otherLinks: ["http://www.sandblessunction.com"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/sand-bless-unction.png",
  },
  {
    index: 78,
    title: "EONIA",
    body: "EONIA is a decentralized real estate platform that allows users to buy sell and tokenize their real estate platform.  Introducing 3d scanning with mobile to upload 3d models of the property.",
    links: {
      github: "https://github.com/mdgolammafuz/EONIA",
      external: "https://supernova.devpost.com/submissions/334586-eonia",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/eonia.png",
  },
  {
    index: 79,
    title: "Blotch",
    body: "Blotch is the first social media fully on ICP that supports rich content (no IPFS or Arweave). With dynamic canister creation and tokenized reporting, Blotch is both scalable and empowers all users.",
    links: {
      github: "https://github.com/am0rlock/blotch",
      livePreview: "http://blotch.one",
      external: "https://supernova.devpost.com/submissions/334149-blotch",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/blotch.png",
  },
  {
    index: 80,
    title: "Dev-Pouch",
    body: "Dev-Pouch is a simple desktop IC wallet based on the Tauri framework.",
    links: {
      github: "https://github.com/GLicDEV/dev-pouch",
      external: "https://supernova.devpost.com/submissions/326893-dev-pouch",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/dev-pouch.gif",
  },
  {
    index: 81,
    title: "Ant Kingdoms, Free play-and-earn NFT Game",
    body: "Ant Kingdoms Free play-and-earn NFT Game is a decentralized game built and runs on Internet Computer.",
    links: {
      github: "https://github.com/NFPTU/dfinity-fu",
      livePreview: "https://fpi33-7qaaa-aaaai-acatq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/326844-ant-kingdoms-free-play-and-earn-nft-game",
      otherLinks: ["https://dfinity-fu.gitbook.io/gamefi-ant"],
    },
    domains: ["GameFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image:
      "/img/community-projects/ant-kingdoms-free-play-and-earn-nft-game.png",
  },
  {
    index: 82,
    title: "Flippy (NFT Barter)",
    body: 'Wouldn\'t it be cool if we could trade NFTs as we did with trading cards when we were kids? "Flippy" is the first platform in the Internet Computer ecosystem that enables the direct exchanges of NFTs.',
    links: {
      github: "https://github.com/Japan-DfinityInfoHub/nft-barter",
      livePreview: "https://a2tci-laaaa-aaaap-qamkq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/333202-flippy-nft-barter",
      otherLinks: [
        "https://github.com/Japan-DfinityInfoHub/generative-art-nft",
      ],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/flippy-(nft-barter).png",
  },
  {
    index: 84,
    title: "PartyBoard",
    body: "WEB3 Metaverse&NFT Social App with inbuilt Game-Fi elements, Social-Fi Protocol, Decentralized Social Audio.",
    links: {
      github: "https://github.com/Pabsysop",
      livePreview: "https://www.partyboard.org/media/partyboard.v8.apk",
      external: "https://supernova.devpost.com/submissions/334470-partyboard",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/partyboard.jpg",
  },
  {
    index: 85,
    title: "Fundnation",
    body: "Fast, secure, decentralized and affordable crowdfunding application powered by internet computer blockchain.",
    links: {
      github: "https://github.com/Fundnation/Fund-Raiser",
      livePreview: "https://jwj2d-5aaaa-aaaap-aahha-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/334360-fundnation",
      otherLinks: [
        "https://www.figma.com/file/pEOaBWUsrs3vFoPAwZao8c/Fundnation?node-id=3%3A4",
        "https://www.figma.com/proto/pEOaBWUsrs3vFoPAwZao8c/Fundnation?page-id=488%3A33640&node-id=499%3A25174&viewport=566%2C498%2C0.06&scaling=min-zoom&starting-point-node-id=499%3A25174&show-proto-sidebar=1",
      ],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/fundnation.png",
  },
  {
    index: 86,
    title: "FIP Coin",
    body: "Free economy for free people",
    links: {
      github: "https://github.com/0xpranav/FIP-Coin",
      external: "https://supernova.devpost.com/submissions/333098-fip-coin",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/fip-coin.png",
  },
  {
    index: 87,
    title: "InfinitySwap Canister SDK",
    body: "An enhanced CDK for Rust Canisters, providing:(1) A framework to test inter-canister communications(2 Compose canister APIs using rust traits.(3) Versioned state management for canister upgrades",
    links: {
      github: "https://github.com/infinity-swap/canister-sdk",
      external:
        "https://supernova.devpost.com/submissions/333189-infinityswap-canister-sdk",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/infinityswap-canister-sdk.png",
  },
  {
    index: 88,
    title: "Finivest",
    body: "Finivest is a money market providing alternative investment and trading strategies to DeFi users on the IC",
    links: {
      github: "https://github.com/HenricoW/findex",
      external: "https://supernova.devpost.com/submissions/333166-finivest",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/finivest.png",
  },
  {
    index: 89,
    title: "ic-py",
    body: "ic-py: Python Agent Library for the Internet Computer",
    links: {
      github: "https://github.com/rocklabs-io/ic-py",
      external: "https://supernova.devpost.com/submissions/333069-ic-py",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["other"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/ic-py.png",
  },
  {
    index: 90,
    title: "Polaris",
    body: "Polaris, a fully transparent internet computer based social trading platform.",
    links: {
      github: "https://github.com/nijna/polaris",
      livePreview:
        "https://drive.google.com/file/d/1gA5d96LHaxe8AZoxJxM1x--1TGEmGf8S/view?usp=sharing",
      external: "https://supernova.devpost.com/submissions/329392-polaris",
      otherLinks: [
        "https://www.figma.com/proto/ec5UGtfRODHZBSGZWc6mJP/Supernova?page-id=204%3A3819&node-id=204%3A10590&viewport=3793%2C1286%2C0.12&scaling=scale-down&starting-point-node-id=204%3A10590",
      ],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/polaris.png",
  },
  {
    index: 91,
    title: "Refound - Mint the art of journalism back to life",
    body: "Refound is an NFT marketplace where journalists and photographers can share first person, creative content from the frontlines swiftly, raise awareness, and sell directly to businesses.",
    links: {
      github: "https://github.com/web3abel/refound-icp",
      livePreview: "https://www.beautiful.ai/player/-N591OF3bb8pBBT-ocWM",
      external:
        "https://supernova.devpost.com/submissions/334332-refound-mint-the-art-of-journalism-back-to-life",
      otherLinks: ["https://superlative-fenglisu-972af1.netlify.app"],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["rust", "motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image:
      "/img/community-projects/refound-mint-the-art-of-journalism-back-to-life.jpeg",
  },
  {
    index: 92,
    title: "NiftiOS",
    body: "NiftiOS is operating system for the creators to bridge Web3 to the posibilites that web3 world brings. \nEnd users don't even need a wallet untill they are ready to do so.",
    links: {
      github: "https://github.com/grmkris/nft-links",
      livePreview: "https://www.niftios.xyz/",
      external: "https://supernova.devpost.com/submissions/334268-niftios",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/niftios.png",
  },
  {
    index: 93,
    title: "Tingram",
    body: "Tingram - your social contacts!",
    links: {
      github: "https://github.com/tingramtingram/dfinity",
      livePreview: "https://m3h3q-wyaaa-aaaap-qabla-cai.ic0.app",
      external: "https://supernova.devpost.com/submissions/326827-tingram",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/tingram.jpeg",
  },
  {
    index: 94,
    title: "LFICO Protocol and Sulfur Network",
    body: "License-Free Initial Coin Offering Protocol And Compliance and Verification Sharing Network",
    links: {
      github: "https://github.com/kentomisawa/sulfur",
      livePreview: "https://github.com/kentomisawa/lfico",
      external:
        "https://supernova.devpost.com/submissions/333978-lfico-protocol-and-sulfur-network",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/lfico-protocol-and-sulfur-network.gif",
  },
  {
    index: 95,
    title: "glue",
    body: "glue allows nft projects to add holder verification to their discord communities. it's easy to use, easy to setup and easily extendable.",
    links: {
      github: "https://github.com/glue-org",
      livePreview:
        "https://discord.com/api/oauth2/authorize?client_id=974260670675697714&permissions=268435456&scope=applications.commands%20bot",
      external: "https://supernova.devpost.com/submissions/327051-glue",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/glue.png",
  },
  {
    index: 96,
    title: "Ukrainian Magicals",
    body: "We create new vision of NFTs with AR Storytellings, AR Face Lenses and Application for it minting, usage and selling",
    links: {
      github:
        "https://github.com/insky/ukrainian-magicals-internet-computer-nft",
      livePreview: "https://dydxz-fqaaa-aaaag-aanla-cai.ic0.app",
      external:
        "https://supernova.devpost.com/submissions/332052-ukrainian-magicals",
      otherLinks: ["https://ukrainianmagicals.fun/"],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/ukrainian-magicals.png",
  },
  {
    index: 97,
    title: "On-chain System of Record with Public Notary",
    body: "We use IC's low cost on-chain storage and inter-canister async calls features to make a cheap and scalable System of Record with Public Notary with features of Oracle, billing and Decrypt+Share.",
    links: {
      github: "https://github.com/amirhyoussefi/ic-sorn",
      external:
        "https://supernova.devpost.com/submissions/334423-on-chain-system-of-record-with-public-notary",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image:
      "/img/community-projects/on-chain-system-of-record-with-public-notary.png",
  },
  {
    index: 98,
    title: "Social Review",
    body: "Decentralized app to collect, validate and reward reviews for various businesses/products. It lets businesses setup a feedback page to encourage interaction and reward tokens to loyal customers.",
    links: {
      github: "https://github.com/sanjivcodes/social_reviews",
      livePreview: "https://7elun-6yaaa-aaaal-aayba-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334576-social-review",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/social-review.jpg",
  },
  {
    index: 99,
    title: "KVERSO",
    body: "KVERSO is a large-scale virtual 3D Metaverse platform based on IC. With 3D Avatars customization, Pet System(KUNO), NFT PFPs(KABI), DIY display features, UGC+PGC, and dress-up functions.",
    links: {
      github: "https://github.com/KVERSO",
      livePreview: "http://www.kverso.com/gallery",
      external: "https://supernova.devpost.com/submissions/334448-kverso",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/kverso.jpg",
  },
  {
    index: 100,
    title: "Dwitter",
    body: "Dwitter is a platform for an interaction between users and celebrities with paid posts and tokenomics",
    links: {
      github: "https://github.com/azhuravel/Dwitter-Dfinity",
      livePreview: "https://oqjv5-vqaaa-aaaai-ack5a-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/333285-dwitter",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/dwitter.png",
  },
  {
    index: 101,
    title: "Thoth Spell Minter",
    body: "Thoth is a generalized tool putting the power of creating complex AI systems into the hands of anyone.",
    links: {
      github: "https://github.com/AtlasFoundation/Thoth/tree/supernova",
      livePreview: "https://f4zho-laaaa-aaaam-qaquq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334383-thoth-spell-minter",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/thoth-spell-minter.jpg",
  },
  {
    index: 102,
    title: "Supernova Deployer",
    body: "An add-on for the Unity3D game engine to help videogame developers deploy NFT for ICP as easily and quickly as possible",
    links: {
      github: "https://github.com/Doc-Failure/Supernova_Deployer",
      external:
        "https://supernova.devpost.com/submissions/332358-supernova-deployer",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/supernova-deployer.png",
  },
  {
    index: 103,
    title: "Nifties",
    body: "A place for the ones who dream.A place where they called 'home' when they're climbing the hill and reaching for the heights.A place to help them chase all the lights and shine.",
    links: {
      github: "https://github.com/o-0-labs",
      livePreview: "https://www.niftiesx.xyz",
      external: "https://supernova.devpost.com/submissions/327541-nifties",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/nifties.jpeg",
  },
  {
    index: 104,
    title: "blank space",
    body: "A space to write, create, think and collaborate on documents with multiple peers across the globe through the IC blockchain.",
    links: {
      github: "https://github.com/mhmemon444/blankspace",
      livePreview: "https://gxneu-6qaaa-aaaal-qax6q-cai.ic0.app/",
      external: "https://supernova.devpost.com/submissions/329795-blank-space",
      otherLinks: ["https://www.blankspace.live/"],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/blank-space.jpeg",
  },
  {
    index: 105,
    title: "FarmDAO",
    body: "Onchain-offchain loans for emerging market agro-processing",
    links: {
      github: "https://github.com/farmdao",
      livePreview: "http://farmdao-app.live/",
      external: "https://supernova.devpost.com/submissions/327515-farmdao",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/farmdao.png",
  },
  {
    index: 106,
    title: "Metablok",
    body: "Metablok is a metaverse shopping& game platform where different brands  that want to sell  in the open-air mall and transfer their real-world products in 3D metaverse and offer them for sale with ICP.",
    links: {
      github: "http://github.com/hasimsait/dfx_deploy",
      livePreview: "https://yp5qx-fyaaa-aaaag-qaovq-cai.raw.ic0.app/",
      external: "https://supernova.devpost.com/submissions/330362-metablok",
      otherLinks: [
        "https://metablok.space/",
        "https://github.com/BeytullahCetin/Metablok-OpenMetaMall",
      ],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/metablok.png",
  },
  {
    index: 107,
    title: "NFTs on Videate",
    body: "Videate is an open video platform that I was awarded a DFNINITY grant for and am in the process of building. For the hackathon, I added NFT purchasing and transferring for all videos on the platform.",
    links: {
      github: "https://github.com/mymikemiller/videate",
      external:
        "https://supernova.devpost.com/submissions/334186-nfts-on-videate",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/nfts-on-videate.png",
  },
  {
    index: 108,
    title: "MantaDocs",
    body: "MantaDocs is a knowledge workspace that lets you create, organize and collaborate on rich documents. From planning your next vacation, to sharing ideas across your team. MantaDocs has you covered.",
    links: {
      github: "https://github.com/jnlewis/manta-ic",
      external: "https://supernova.devpost.com/submissions/334201-mantadocs",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/mantadocs.png",
  },
  {
    index: 109,
    title: "WEB3 Empowered Marketing Advisor",
    body: "Get a Marketing Advise from over 200 Marketing Expert, based on your situation, product and target group with an exact guideline how to do your marketing. Fully on Web3 build on the Internet Computer.",
    links: {
      github: "https://github.com/MCikus/supernova-submission",
      livePreview: "http://ufostart-supernova.icp.xyz/landing",
      external:
        "https://supernova.devpost.com/submissions/334198-web3-empowered-marketing-advisor",
      otherLinks: ["http://ufostart-supernova.icp.xyz"],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["javascript", "motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/web3-empowered-marketing-advisor.png",
  },
  {
    index: 110,
    title: "Generalized DEX",
    body: "A new type of swappable DEX, which is gasless, feeless, debtless short-able, and extremely extensible to various logic",
    links: {
      github: "https://github.com/kentomisawa/generalized-dex",
      livePreview:
        "https://docs.google.com/document/d/1QqzhxLDBoQcvZSrotmO9biPbV5w3oI-xnofYA0aFVQk/edit?usp=sharing",
      external:
        "https://supernova.devpost.com/submissions/331056-generalized-dex",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/generalized-dex.gif",
  },
  {
    index: 111,
    title: "Mini Desktop",
    body: "A desktop that knows no bounds.",
    links: {
      github: "https://github.com/amitsingh19975/destop-on-blockchain",
      external: "https://supernova.devpost.com/submissions/333334-mini-desktop",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/mini-desktop.png",
  },
  {
    index: 112,
    title: "Q messaging system",
    body: "Q is an uncensored open source messaging system.Q is written in the Motoko language of internet computer ICP.One of the aims is to give a unified identity to the multitude of anonymous people.",
    links: {
      github: "https://github.com/metaquid/Q-messaging-system",
      livePreview: "https://meize-wiaaa-aaaan-qamyq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334359-q-messaging-system",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["motoko", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/q-messaging-system.png",
  },
  {
    index: 113,
    title: "Dynamic Rarity NFTs",
    body: "Dynamically changing rarities",
    links: {
      github: "https://github.com/barolukluk/dynamic_rarity_nfts",
      livePreview: "https://x7qdv-qyaaa-aaaan-qacgq-cai.raw.ic0.app",
      external:
        "https://supernova.devpost.com/submissions/334490-dynamic-rarity-nfts",
      otherLinks: ["https://bootcamp-faucet.vercel.app/"],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["motoko"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/dynamic-rarity-nfts.gif",
  },
  {
    index: 114,
    title: "BTC Lending Protocol",
    body: "Access your Bitcoin's value today.\n\nA port of Ethereum's Liquity and Solana's Hedge onto the IC. Instead of using ICP as the primary hedging token, native Bitcoin is used.",
    links: {
      github: "https://github.com/dangdennis/btc-lending-protocol",
      external:
        "https://supernova.devpost.com/submissions/334250-btc-lending-protocol",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/btc-lending-protocol.png",
  },
  {
    index: 115,
    title: "IC metamask",
    body: "IC metamask",
    links: {
      github: "https://github.com/aewc/ic-signer/tree/supernova",
      external: "https://supernova.devpost.com/submissions/328278-ic-metamask",
      otherLinks: [],
    },
    domains: ["Public Good / Social Impact"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/ic-metamask.gif",
  },
  {
    index: 116,
    title: "Invoices as NFTs",
    body: "Invoices as NFTs is a quick demo that deals with enabling Premium features on your dApp without dealing with the ledger, via an invoice canister.",
    links: {
      github: "https://github.com/GLicDEV/invoices_as_nft",
      livePreview: "https://t5izh-jqaaa-aaaai-qngjq-cai.ic0.app/",
      external:
        "https://supernova.devpost.com/submissions/334600-invoices-as-nfts",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/invoices-as-nfts.gif",
  },
  {
    index: 117,
    title: "My Status",
    body: 'My Status is a social media platform that allows users to share daily events of their lives with friends in the form of "statuses".',
    links: {
      github: "https://github.com/aymanfmustafa/My-Status",
      livePreview: "https://testflight.apple.com/join/cKTspEFY",
      external: "https://supernova.devpost.com/submissions/327580-my-status",
      otherLinks: [],
    },
    domains: ["SocialFi"],
    level: "advanced",
    languages: ["motoko", "rust", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/my-status.jpg",
  },
  {
    index: 118,
    title: "LaunchTrail",
    body: "Bring 100% verifiability to Internet Computer projects and make them more secure and dependable.",
    links: {
      github: "https://github.com/spinner-cash/launchtrail",
      external: "https://supernova.devpost.com/submissions/327084-launchtrail",
      otherLinks: [],
    },
    domains: ["Blue Sky"],
    level: "advanced",
    languages: ["rust"],
    contentType: ["code samples", "community repo"],
    image: "/img/community-projects/launchtrail.png",
  },
  {
    index: 119,
    title: "React Website with Contentful CMS",
    body: "This is a boilerplate for you to easily setup and deploy a React website with Contentful CMS onto the Internet Computer blockchain.",
    image: "/img/community-projects/react-website-with-contentful-cms.png",
    links: {
      github: "https://github.com/therealbryanho/dfinity-websitewithcms",
      otherLinks: [],
    },
    domains: ["Website"],
    languages: ["javascript"],
    level: "intermediate",
    contentType: ["code samples"],
  },
  {
    index: 120,
    title: "Simple Blogsite",
    body: "Learn how to make your own blog supporting CRUD operations in Motoko on the Internet Computer.",
    image: "/img/community-projects/simpleblog.png",
    links: {
      github: "https://github.com/lukasvozda/icblog",
      livePreview: "https://gaqra-oqaaa-aaaah-qc4qa-cai.ic0.app",
      otherLinks: [],
    },
    domains: ["Website"],
    languages: ["motoko", "javascript"],
    level: "beginner",
    contentType: ["code samples", "community repo", "live demos"],
  },
  {
    index: 121,
    title: "Sending Emails on IC",
    body: "An example on how to use internet identity to authenticate and send emails via courier",
    image: "/img/community-projects/emailer.png",
    links: {
      github: "https://github.com/ArgonStudiosXYZ/ic-emailer",
      otherLinks: [],
    },
    domains: ["Website"],
    languages: ["motoko", "javascript"],
    level: "advanced",
    contentType: ["code samples", "community repo", "live demos"],
  },
  {
    index: 122,
    title: "ERC-721 NFT with metadata on IC",
    body: "Learn how to mint an ERC-721 NFT on Ethereum/Polygon with canister-served metadata.",
    image: "/img/community-projects/122_erc721_tutorial.jpg",
    links: {
      github: "https://github.com/domwoe/erc-721-ic-assets",
      otherLinks: [],
    },
    domains: ["Metaverse and NFTs"],
    languages: ["motoko", "javascript"],
    level: "beginner",
    contentType: ["code samples", "community repo", "tutorial"],
  },
  {
    index: 123,
    title: "No Key Wallet",
    body: "Sign transactions for EVM-compatible blockchains on the Internet Computer.",
    image: "/img/community-projects/no_key_wallet.png",
    links: {
      github: "https://github.com/nikolas-con/ic-evm-sign-starter",
      livePreview: "https://vqbpb-giaaa-aaaap-qaxda-cai.ic0.app",
      external: "https://www.tzionis.com/projects/ic-evm-sign",
      docs: "https://github.com/nikolas-con/ic-evm-sign",
      otherLinks: [],
    },
    domains: ["Asynchronous DeFi"],
    languages: ["rust", "javascript"],
    level: "intermediate",
    contentType: ["code samples", "community repo", "tutorial"],
  },
  {
    index: 124,
    title: "Uniswap Interface on IC",
    body: "Demo of Uniswap Interface on the IC with canister-based signer.",
    image: "/img/community-projects/uniswap_ui_on_ic.jpg",
    links: {
      github: "https://github.com/domwoe/uniswap_ui_on_ic",
      livePreview: "https://yrog5-xqaaa-aaaap-qa5za-cai.ic0.app/",
      otherLinks: [],
    },
    domains: ["Website"],
    languages: ["rust", "javascript"],
    level: "beginner",
    contentType: ["code samples", "community repo", "live demos"],
  },
  {
    index: 125,
    title: "Bitshop",
    body: "A proof of concept project that demonstrates capabilities of the Internet Computer blockchain to serve as a Bitcoin e-shop.",
    image: "/img/community-projects/bitshop.png",
    links: {
      github: "https://github.com/lukasvozda/bitshop",
      livePreview: "https://ughim-6qaaa-aaaah-qc7qa-cai.ic0.app/",
      otherLinks: [],
    },
    domains: ["Website"],
    languages: ["motoko", "javascript"],
    level: "beginner",
    contentType: ["code samples", "community repo", "live demos"],
  },
  {
    index: 126,
    title: "D-VOTE",
    body: "Voting on the blockchain, and the vote results are transparent and can not be tampered with.",
    links: {
      github: "https://github.com/NewbMiao/dvote",
      livePreview: "https://7y3zv-rqaaa-aaaag-abswa-cai.icp0.io/",
      otherLinks: [],
    },
    domains: ["Website"],
    level: "advanced",
    languages: ["rust", "javascript"],
    contentType: ["code samples", "community repo", "live demos"],
    image: "/img/community-projects/d-vote.png",
  },
];

export default communityProjects;
