const completedRoadmapItems = [
  {
    title: "Motoko Smart Contract Language",
    description:
      "Motoko is a new programming language for smart contracts. It is designed to seamlessly support the programming model of the Internet Computer and makes it easier to take advantage of the unique features of the blockchain. Motoko is strongly typed, actor-based, and has built-in support for orthogonal persistence and asynchronous message passing. Productivity and safety features include automatic memory management, generics, type inference, pattern matching, and both arbitrary- and fixed-precision arithmetic. Messaging transparently employs the Internet Computer’s Candid interface definition language and wire format for typed, high-level, and cross-language interoperability.",
    image: "/img/roadmap/completed/motoko.jpeg",
    link: "/how-it-works/motoko",
  },
  {
    title: "Chain Key Cryptography",
    description:
      "Chain Key cryptography is one of the fundamental breakthroughs enabling the Internet Computer to scale to millions of nodes. The most notable innovation of Chain Key cryptography is that the Internet Computer has a single public key, which enables any device to verify the authenticity of artifacts generated by the Internet Computer, even smart watches and mobile phones.",
    image: "/img/roadmap/completed/chain-key-cryptography.jpeg",
    link: "/how-it-works/chain-key-technology",
  },
  {
    title: "NNS: Internet Computer Blockchain Governance",
    description:
      "The Network Nervous System (NNS) is the open algorithmic system governing the Internet Computer blockchain. Its most notable innovations include its ability to upgrade the Internet Computer protocol and software running on node machines, onboard new node providers, add node machines into the blockchain network, and create new subnet blockchains to increase capacity. Anyone can participate in the NNS by staking ICP tokens into one or more neurons. Neurons can submit proposals and decide to adopt or reject them. The NNS implements liquid democracy: neurons can follow other neurons a delegate voting power.",
    image: "/img/roadmap/completed/nns.jpeg",
    link: "/how-it-works/network-nervous-system-nns",
  },
  {
    title: "Noninteractive Distributed Key Generation",
    description:
      "NIDKG is a cryptographic protocol to distributedly generate key shares for each of the nodes participating in a subnet blockchain. It applies advanced cryptography, including encryption with forward secrecy and noninteractive zero-knowledge proofs of correct key sharing.",
    image: "/img/roadmap/completed/ndkg.jpeg",
    link: "/how-it-works/chain-key-technology",
  },
  {
    title: "Internet Identity: Anonymizing Blockchain Authentication System",
    description:
      "Today, the main means of identity and authentication prevalently used online are usernames and passwords. The Internet Computer blockchain has replaced this model with a more advanced and much more secure method of cryptographic authentication that is more convenient, works across all of a user's devices, and helps to protect user privacy. ",
    image: "/img/roadmap/completed/internet-identity.jpeg",
    link: "/how-it-works/web-authentication-identity",
  },
  {
    title: "Internet Computer Consensus",
    description:
      "The Internet Computer blockchain runs on a network of nodes in independent data centers located around the world. In each of its subnet blockchains, the participating nodes must process the same messages in the same order to ensure that they achieve the same state. To this end, the Internet Computer relies on a novel consensus protocol, as described in this presentation.",
    image: "/img/roadmap/completed/consensus.jpeg",
    link: "/how-it-works/consensus",
  },
];

export default completedRoadmapItems;
