export const dfinityToolingItems = [
  {
    title: "dfx",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["CLI", "development", "operations"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Motoko VS Code",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["plugin", "development"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "didc",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["CLI", "development"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "quill",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["CLI", "development"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "sns-quill",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["CLI"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "ic-js",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["library"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Vessel Package Manager",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["development", "CLI"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  /*{
        index: 1,
        title: "dfx",
        image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
        domains: ["Asynchronous DeFi"],
        tags: ["CLI", "dev", "op"],
        languages: ["motoko", "rust"],
        level: "advanced",
        contentType: ["code samples", "documentation", "live demos"],
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        links: {
          action: {
            text: "Get code",
            to: "https://github.com/dfinity/examples/tree/master/motoko/basic_bitcoin",
          },
          motoko:
              "https://github.com/dfinity/examples/tree/master/motoko/basic_bitcoin",
          rust: "https://github.com/dfinity/examples/tree/master/rust/basic_bitcoin",
          docs: "/docs/current/samples/deploying-your-first-bitcoin-dapp",
        },
      },*/
];
export const communityToolingItems = [
  {
    title: "ic-repl",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["development", "operations", "testing"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "connect2ic",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["library"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "IC Inspector",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["plugin", "development", "operations", "testing"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Launchtrail",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["library", "operations"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Cover",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["operations"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Canistergeek",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["library", "operations"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Sudograph",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["library", "database"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "CanDB",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["library", "database"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "CAP",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["database", "operations"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "Intellij Candid Plugin",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["plugin", "development"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "create-ic",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["CLI", "starter"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  {
    title: "create-ic-app",
    image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
    domains: ["Asynchronous DeFi"],
    tags: ["CLI", "starter"],
    languages: ["motoko", "rust"],
    level: "advanced",
    contentType: ["code samples", "documentation", "live demos"],
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    links: ["/"],
  },
  /*{
        index: 1,
        title: "dfx",
        image: require("../../../static/img/tooling/Tooling-cover.jpeg").default,
        domains: ["Asynchronous DeFi"],
        tags: ["CLI", "dev", "op"],
        languages: ["motoko", "rust"],
        level: "advanced",
        contentType: ["code samples", "documentation", "live demos"],
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        links: {
          action: {
            text: "Get code",
            to: "https://github.com/dfinity/examples/tree/master/motoko/basic_bitcoin",
          },
          motoko:
              "https://github.com/dfinity/examples/tree/master/motoko/basic_bitcoin",
          rust: "https://github.com/dfinity/examples/tree/master/rust/basic_bitcoin",
          docs: "/docs/current/samples/deploying-your-first-bitcoin-dapp",
        },
      },*/
];
