# Add SDK Orbit wallet as a controller to hwvjt-wqaaa-aaaam-qadra-cai
# This is an old canister that is coming up in google results

name: Add controller

on:
  workflow_dispatch:
    # Allows manual triggering

jobs:
  add-controller:
    name: "Add a controller"
    runs-on: ubuntu-latest

    environment:
      name: "Internet Computer Mainnet"
      url: ${{ steps.get-url.outputs.url }}

    steps:

      - name: Install ICP-CLI
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/dfinity/icp-cli/releases/download/v0.1.0/icp-cli-installer.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup Identity
        run: |
          mkdir -p ~/.local/share/icp-cli/identity/keys
          echo $ICP_IDENTITY_PORTAL_DEPLOY > ~/.local/share/icp-cli/identity/keys/portal-deploy.pem
          sed -i 's/\\r\\n/\r\n/g' ~/.local/share/icp-cli/identity/keys/portal-deploy.pem
          icp identity import portal-deploy --from-pem ~/.local/share/icp-cli/identity/keys/portal-deploy.pem --storage plaintext
          icp identity default portal-deploy
        env:
          ICP_IDENTITY_PORTAL_DEPLOY: ${{ secrets.DFX_IDENTITY }}

      - name: Add SDK Orbit as a controller
        run: |
          icp canister settings update -n ic --add-controller gilo4-xaaaa-aaaah-qqakq-cai hwvjt-wqaaa-aaaam-qadra-cai
