name: "check cddl and candid files"
on:
  pull_request:
    paths:
      - docs/references/_attachments/certificates.cddl
      - docs/references/_attachments/requests.cddl
      - docs/references/_attachments/http-gateway.did
      - docs/references/_attachments/ic.did
  push:
    branches:
      - main
jobs:
  cddl-candid:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check cddl files
      run: |
        docker run --rm -v $PWD/docs/references/_attachments:/workdir ghcr.io/anweiss/cddl-cli:0.9.1 compile-cddl --cddl /workdir/certificates.cddl
        docker run --rm -v $PWD/docs/references/_attachments:/workdir ghcr.io/anweiss/cddl-cli:0.9.1 compile-cddl --cddl /workdir/requests.cddl
    - name: Check candid files
      run: |
        curl -L https://github.com/dfinity/candid/releases/download/2023-07-25/didc-linux64 -o didc
        chmod +x didc
        ./didc check docs/references/_attachments/http-gateway.did
        ./didc check docs/references/_attachments/ic.did
