name: Validate Docs PR comments
on:
  issue_comment:
    types: [created]
    paths:
      - docs/developer-docs/

jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - uses: actions/setup-node@v4
       with:
          node-version: 20
     - uses: actions/github-script@v6
       if: contains(github.event.comment.body, 'I agree that I have run the commands and code included in this PR and have confirmed their accuracy and functionality.')
       with:
          script: |
            const comments = require('./.github/workflows/scripts/comments.js');
            await comments.create(context, github, `PR content has been validated by a reviewer.`);
       env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
