name: Validate Docs PR comments
on:
  issue_comment:
    types: [created]
    paths:
      - docs/developer-docs/
    
jobs:
  docs-tag:
    name: Tag PR with documentation
    permissions: write-all
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Tag PR with documentation
      run: |
        gh pr edit ${{ github.event.pull_request.number }} --add-label documentation
