on:
  issue_comment:
    types: [created]
    paths:
      - docs/developer-docs/
jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR comments
        if: contains(github.event.comment.body, 'I agree that I have run the commands and code included in this PR and have confirmed their accuracy and functionality.')
        run: echo ${{ steps.fc.outputs.comment-author }}
