on:
  issue_comment:
    types: [created]
    paths:
      - docs/developer-docs/
jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR comments
        if: contains(github.event.comment.body, 'I agree that I have run the commands and code included in this PR and have confirmed their accuracy and functionality.')
        run: echo "PR has been commented on."      
      - name: Comment on PR  
        uses: actions/github-script@v6
        with:
          script: |
              const comments = require('./.github/workflows/scripts/comments.js');
              await comments.create(context, github, `PR content has been validated by a reviewer.`);
